# Generated by Django 2.0.7 on 2020-01-02 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datafile', models.FileField(blank=True, null=True, upload_to='')),
                ('graph_type', models.CharField(max_length=10)),
                ('x_axis', models.CharField(max_length=100)),
                ('y_axis', models.CharField(max_length=100)),
                ('dash_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dash.Dashboard')),
            ],
        ),
    ]
